"""students description column

Revision ID: 05cbef92bce8
Revises: 29dbb0a00879
Create Date: 2019-12-13 10:20:44.718260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cbef92bce8'
down_revision = '29dbb0a00879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'description')
    # ### end Alembic commands ###
