"""empty message

Revision ID: 07d306bd6567
Revises: 5d38e4bda2ba
Create Date: 2019-08-28 14:30:37.656387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07d306bd6567'
down_revision = '5d38e4bda2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('path', sa.Unicode(length=128), nullable=True))
    op.alter_column('schedule', 'type_of_course',
               existing_type=postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_course'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'type_of_course',
               existing_type=postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_course'),
               nullable=False)
    op.drop_column('course', 'path')
    # ### end Alembic commands ###
