"""taugh_course db.backref

Revision ID: 0d66f9aac568
Revises: 85da177c3ec6
Create Date: 2019-11-11 21:36:02.817727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d66f9aac568'
down_revision = '85da177c3ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
