"""requisition shcedules

Revision ID: 128f73c2d601
Revises: 445c188f22dd
Create Date: 2019-09-24 07:26:45.701455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '128f73c2d601'
down_revision = '445c188f22dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisition_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),

    sa.Column('type_of_class', postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_class', create_type=False), nullable=False),

    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scheduleday', sa.Column('requisition_schedule_id', sa.Integer(), nullable=True))
    op.alter_column('scheduleday', 'day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    op.create_foreign_key(None, 'scheduleday', 'requisition_schedule', ['requisition_schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduleday', type_='foreignkey')
    op.alter_column('scheduleday', 'day',
               existing_type=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    op.drop_column('scheduleday', 'requisition_schedule_id')
    op.drop_table('requisition_schedule')
    # ### end Alembic commands ###
