"""remove course_id from payment

Revision ID: 15bcca64fd8b
Revises: 62e2b6e70b1b
Create Date: 2019-10-21 17:29:55.950297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bcca64fd8b'
down_revision = '62e2b6e70b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_course_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_course_id_fkey', 'payment', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
