"""nullable=True schedule_id and requisition_schedule_id

Revision ID: 1bd86ba80ded
Revises: 59e9c7285270
Create Date: 2019-09-24 09:02:23.811019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bd86ba80ded'
down_revision = '59e9c7285270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    op.alter_column('schedule_day_and_time', 'requisition_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule_day_and_time', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_day_and_time', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule_day_and_time', 'requisition_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###
