"""rename COORDINATED_WITH_TEACHER with COORDINATING

Revision ID: 29dbb0a00879
Revises: b29a445c7b3d
Create Date: 2019-11-22 17:39:46.846722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29dbb0a00879'
down_revision = 'b29a445c7b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisition_schedule', 'requisition_status',
               existing_type=postgresql.ENUM('STUDENT_REQUISITION', 'COORDINATED_WITH_TEACHER', 'APPROVED', name='requisition_schedule_status'),
               type_=sa.Enum('STUDENT_REQUISITION', 'COORDINATING', 'APPROVED', name='requisition_schedule_status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisition_schedule', 'requisition_status',
               existing_type=sa.Enum('STUDENT_REQUISITION', 'COORDINATING', 'APPROVED', name='requisition_schedule_status'),
               type_=postgresql.ENUM('STUDENT_REQUISITION', 'COORDINATED_WITH_TEACHER', 'APPROVED', name='requisition_schedule_status'),
               existing_nullable=True)
    # ### end Alembic commands ###
