"""foreignkey payment on schedule

Revision ID: 2a125e5ee346
Revises: 4b12cae0f01c
Create Date: 2019-09-11 16:56:59.697781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a125e5ee346'
down_revision = '4b12cae0f01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.alter_column('schedule', 'schedule_day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    op.create_foreign_key(None, 'schedule', 'payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.alter_column('schedule', 'schedule_day',
               existing_type=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    op.drop_column('schedule', 'payment_id')
    # ### end Alembic commands ###
