"""last_education

Revision ID: 2b343dca2231
Revises: ac48c83d7e89
Create Date: 2019-07-11 14:39:34.471247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b343dca2231'
down_revision = 'ac48c83d7e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_education', sa.String(), nullable=True))
    op.drop_column('student', 'education')
    op.add_column('teacher', sa.Column('last_education', sa.String(), nullable=True))
    op.drop_column('teacher', 'education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'last_education')
    op.add_column('student', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student', 'last_education')
    # ### end Alembic commands ###
