"""add note column to payment

Revision ID: 2f581d6350fd
Revises: 7d27b5b2dc87
Create Date: 2019-11-03 08:09:30.992624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f581d6350fd'
down_revision = '7d27b5b2dc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'note')
    # ### end Alembic commands ###
