"""set nullable=True to start and end_at scheduleday

Revision ID: 445c188f22dd
Revises: 31167a2bb24f
Create Date: 2019-09-23 20:44:46.077746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '445c188f22dd'
down_revision = '31167a2bb24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduleday', 'day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduleday', 'day',
               existing_type=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###
