"""remove payment_for_month

Revision ID: 4df6eccac831
Revises: e560894e1569
Create Date: 2019-10-11 14:00:10.594936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4df6eccac831'
down_revision = 'e560894e1569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_for_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_for_month', postgresql.ENUM('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', name='payment_for_month'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
