"""delete column schedule_month on Schedule model

Revision ID: 5881e8ab3988
Revises: 9a50910ccef0
Create Date: 2019-09-15 20:42:31.924392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5881e8ab3988'
down_revision = '9a50910ccef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'schedule_day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    op.drop_column('schedule', 'schedule_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('schedule_month', postgresql.ENUM('January', 'February', 'March', 'April', 'May', 'June', 'July', 'Augustus', 'September', 'October', 'November', 'December', name='schedule_month'), autoincrement=False, nullable=True))
    op.alter_column('schedule', 'schedule_day',
               existing_type=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    # ### end Alembic commands ###
