"""rename shcedule_day_and_time

Revision ID: 59e9c7285270
Revises: 128f73c2d601
Create Date: 2019-09-24 07:51:32.516782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59e9c7285270'
down_revision = '128f73c2d601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_day_and_time',
    sa.Column('id', sa.Integer(), nullable=False),

    sa.Column('day', postgresql.ENUM('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day', create_type=False), nullable=True),

    sa.Column('start_at', sa.Time(), nullable=True),
    sa.Column('end_at', sa.Time(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('requisition_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_schedule_id'], ['requisition_schedule.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduleday')
    op.alter_column('requisition_schedule', 'type_of_class',
               existing_type=postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_class'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisition_schedule', 'type_of_class',
               existing_type=postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_class'),
               nullable=False)
    op.create_table('scheduleday',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requisition_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requisition_schedule_id'], ['requisition_schedule.id'], name='scheduleday_requisition_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='scheduleday_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduleday_pkey')
    )
    op.drop_table('schedule_day_and_time')
    # ### end Alembic commands ###
