"""remove payment_id from schedule model

Revision ID: 61a83e70a6b2
Revises: eae16dbe9e85
Create Date: 2019-10-20 16:28:37.760816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a83e70a6b2'
down_revision = 'eae16dbe9e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_payment_id_fkey', 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'payment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('schedule_payment_id_fkey', 'schedule', 'payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###
