"""move type_of_class from payment to schedule

Revision ID: 62e2b6e70b1b
Revises: 451d4e42aead
Create Date: 2019-10-20 16:35:21.763358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62e2b6e70b1b'
down_revision = '451d4e42aead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'type_of_class')
    op.add_column('schedule', sa.Column('type_of_class', sa.Enum('REGULAR', 'PRIVATE', name='type_of_class'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'type_of_class')
    op.add_column('payment', sa.Column('type_of_class', postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_class'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
