"""type_of_course field

Revision ID: 680598af33a0
Revises: 2b343dca2231
Create Date: 2019-07-11 15:06:10.943785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '680598af33a0'
down_revision = '2b343dca2231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    type_of_course = postgresql.ENUM('PRIVATE', 'REGULAR', name='type_of_course')
    type_of_course.create(op.get_bind())
    op.add_column('course', sa.Column('type_of_course', sa.Enum('REGULAR', 'PRIVATE', name='type_of_course'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'type_of_course')
    type_of_course = postgresql.ENUM('PRIVATE', 'REGULAR', name='type_of_course')
    type_of_course.create(op.get_bind())
    # ### end Alembic commands ###
