"""remove type of class from schedule model

Revision ID: 786f8bfc1e16
Revises: 9e4f9c9593ac
Create Date: 2019-10-03 17:27:27.785356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '786f8bfc1e16'
down_revision = '9e4f9c9593ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'type_of_class')
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    op.add_column('schedule', sa.Column('type_of_class', postgresql.ENUM('REGULAR', 'PRIVATE', name='type_of_class'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
