"""empty message

Revision ID: 7c8c6818ddc1
Revises: 07d306bd6567
Create Date: 2019-08-28 17:45:29.119900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8c6818ddc1'
down_revision = '07d306bd6567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('image', sa.Unicode(length=128), nullable=True))
    op.drop_column('course', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('path', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('course', 'image')
    # ### end Alembic commands ###
