"""remove taught_courses association table and make new many-to-many taught_course model

Revision ID: 85da177c3ec6
Revises: 87dab5b27070
Create Date: 2019-11-11 21:11:54.159916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85da177c3ec6'
down_revision = '87dab5b27070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taught_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('taught_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taught_courses',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='taught_courses_course_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='taught_courses_teacher_id_fkey', onupdate='CASCADE', ondelete='CASCADE')
    )
    op.drop_table('taught_course')
    # ### end Alembic commands ###
