"""modify payment_status | add warning_1, warning_2 and warning_3 status

Revision ID: 87dab5b27070
Revises: 9852af274c88
Create Date: 2019-11-06 20:24:13.857380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dab5b27070'
down_revision = '9852af274c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
