""".

Revision ID: 91fc74acc3f0
Revises: 
Create Date: 2019-07-10 11:39:07.936506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fc74acc3f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('address')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
    # op.drop_column('users', 'date_of_birth')
    # op.drop_column('users', 'address')
    # op.drop_column('users', 'updated_at')
    # op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
