"""add "-" mark to DayNameList

Revision ID: 949383e60cc0
Revises: 786f8bfc1e16
Create Date: 2019-10-04 11:17:34.109164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '949383e60cc0'
down_revision = '786f8bfc1e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_day_and_time', 'day',
               existing_type=sa.Enum('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day'),
               existing_nullable=True)
    # ### end Alembic commands ###
