"""note column on requisition schedule

Revision ID: b29a445c7b3d
Revises: d2d68de4e98c
Create Date: 2019-11-20 14:39:52.451720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29a445c7b3d'
down_revision = 'd2d68de4e98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisition_schedule', sa.Column('note', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisition_schedule', 'note')
    # ### end Alembic commands ###
