"""how_many_times_in_a_week

Revision ID: bd69d7751aac
Revises: 4df6eccac831
Create Date: 2019-10-11 14:59:21.433323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd69d7751aac'
down_revision = '4df6eccac831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('how_many_times_in_a_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'how_many_times_in_a_week')
    # ### end Alembic commands ###
