"""requisition_schedule_status

Revision ID: d2d68de4e98c
Revises: 0d66f9aac568
Create Date: 2019-11-20 09:48:05.582197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d68de4e98c'
down_revision = '0d66f9aac568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisition_schedule', sa.Column('requisition_status', sa.Enum('STUDENT_REQUISITION', 'COORDINATED_WITH_TEACHER', 'APPROVED', name='requisition_schedule_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisition_schedule', 'requisition_status')
    # ### end Alembic commands ###
