""".

Revision ID: d4382547e743
Revises: 37e427cbbb83
Create Date: 2019-07-10 11:50:01.186933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4382547e743'
down_revision = '37e427cbbb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
