"""remove course_status

Revision ID: da62d44c9705
Revises: e7ec3e0a89c2
Create Date: 2019-10-10 17:14:39.216569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da62d44c9705'
down_revision = 'e7ec3e0a89c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'course_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('course_status', postgresql.ENUM('PENDING', 'RUNNING', 'FINISHED', name='course_status'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
