"""add some course details

Revision ID: e57a2d730028
Revises: bd69d7751aac
Create Date: 2019-10-14 10:52:38.668400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57a2d730028'
down_revision = 'bd69d7751aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('min_private_class_charge_per_meet', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('min_private_class_duration', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('min_regular_class_charge_per_meet', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('min_regular_class_duration', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('private_class_charge_per_minutes', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('regular_class_charge_per_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'regular_class_charge_per_minutes')
    op.drop_column('course', 'private_class_charge_per_minutes')
    op.drop_column('course', 'min_regular_class_duration')
    op.drop_column('course', 'min_regular_class_charge_per_meet')
    op.drop_column('course', 'min_private_class_duration')
    op.drop_column('course', 'min_private_class_charge_per_meet')
    # ### end Alembic commands ###
