"""rename schedule_day_and_time to time_schedule

Revision ID: e7ec3e0a89c2
Revises: ed187c2f13ba
Create Date: 2019-10-10 16:36:04.369290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7ec3e0a89c2'
down_revision = 'ed187c2f13ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', postgresql.ENUM('None_choice', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='day', create_type=False), nullable=True),
    sa.Column('start_at', sa.Time(), nullable=True),
    sa.Column('end_at', sa.Time(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('requisition_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_schedule_id'], ['requisition_schedule.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule_day_and_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_day_and_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', ' ', 'None_choice', name='day'), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requisition_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requisition_schedule_id'], ['requisition_schedule.id'], name='schedule_day_and_time_requisition_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='schedule_day_and_time_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='schedule_day_and_time_pkey')
    )
    op.drop_table('time_schedule')
    # ### end Alembic commands ###
