"""some revision on schedule, taugh_courses array

Revision ID: fb2641acd64d
Revises: f313d14e0d39
Create Date: 2019-09-14 13:52:54.700748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import INTEGER
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb2641acd64d'
down_revision = 'f313d14e0d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'schedule_day',
               existing_type=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    op.alter_column('taught_courses', 'teacher_id',
               existing_type=postgresql.ARRAY(INTEGER()),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'taught_courses', 'teacher', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'taught_courses', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taught_courses', type_='foreignkey')
    op.drop_constraint(None, 'taught_courses', type_='foreignkey')
    op.alter_column('taught_courses', 'teacher_id',
               existing_type=sa.Integer(),
               type_=postgresql.ARRAY(INTEGER()),
               existing_nullable=True)
    op.alter_column('schedule', 'schedule_day',
               existing_type=sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wenesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               type_=postgresql.ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='schedule_day'),
               existing_nullable=True)
    # ### end Alembic commands ###
